name: Run Unit Tests

# Trigger the workflow on push to main branch and on pull requests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install main application dependencies
        pip install -r requirements.txt
        # Install any test dependencies if needed
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    
    - name: Run unit tests
      run: |
        # Run tests with verbose output
        python tests/test_parse_file.py
    
    - name: Run test runner
      run: |
        # Also run with our custom test runner
        python run_tests.py 